//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBVault.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string Operation { get; set; }
        public string Information { get; set; }
    
        public virtual KbUser KbUser { get; set; }
    }
}
