//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBVault.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleTag
    {
        public long Id { get; set; }
        public long TagId { get; set; }
        public long ArticleId { get; set; }
    
        public virtual Tag Tag { get; set; }
        public virtual Article Article { get; set; }
    }
}
