//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBVault.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public long Id { get; set; }
        public long ArticleId { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
        public string Extension { get; set; }
        public int Downloads { get; set; }
        public string Hash { get; set; }
        public Nullable<System.DateTime> HashTime { get; set; }
        public string MimeType { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
