//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBVault.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class KbUser
    {
        public KbUser()
        {
            this.Articles = new HashSet<Article>();
            this.Activities = new HashSet<Activity>();
            this.ArticleTags = new HashSet<ArticleTag>();
            this.Attachments = new HashSet<Attachment>();
            this.Categories = new HashSet<Category>();
            this.KbUser1 = new HashSet<KbUser>();
            this.Settings = new HashSet<Setting>();
            this.Tags = new HashSet<Tag>();
        }
    
        public long Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        public long Author { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<ArticleTag> ArticleTags { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<KbUser> KbUser1 { get; set; }
        public virtual KbUser KbUser2 { get; set; }
        public virtual ICollection<Setting> Settings { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
