//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBVault.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string CompanyName { get; set; }
        public string TagLine { get; set; }
        public string JumbotronText { get; set; }
        public short ArticleCountPerCategoryOnHomePage { get; set; }
        public string ShareThisPublicKey { get; set; }
        public string DisqusShortName { get; set; }
        public string IndexFileExtensions { get; set; }
    }
}
