//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBVault.Dal
{
    using System;
    
    public partial class SimilarArticle
    {
        public Nullable<long> Id { get; set; }
        public string SefName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PublishEndDate { get; set; }
        public Nullable<System.DateTime> PublishStartDate { get; set; }
        public Nullable<int> IsDraft { get; set; }
        public Nullable<int> Relevance { get; set; }
    }
}
