//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBVault.Dal
{
    using System;
    
    public partial class TopTagItem
    {
        public Nullable<int> Ratio { get; set; }
        public string Name { get; set; }
        public Nullable<long> Id { get; set; }
        public int FontSize { get; set; }
    }
}
