//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBVault.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KBVault.Web.Resources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Attachment?.
        /// </summary>
        public static string ArticleAttachmentRemoveConfirmation {
            get {
                return ResourceManager.GetString("ArticleAttachmentRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string ArticleCreatePageArticleTabTitle {
            get {
                return ResourceManager.GetString("ArticleCreatePageArticleTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort Upload.
        /// </summary>
        public static string ArticleCreatePageAttachmentAbortText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentAbortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Upload.
        /// </summary>
        public static string ArticleCreatePageAttachmentCancelText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ArticleCreatePageAttachmentDeleteText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string ArticleCreatePageAttachmentDoneText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Files Here.
        /// </summary>
        public static string ArticleCreatePageAttachmentDragDropText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentDragDropText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments are available after saving article..
        /// </summary>
        public static string ArticleCreatePageAttachmentsAfterSaveMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentsAfterSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string ArticleCreatePageAttachmentsHeader {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string ArticleCreatePageAttachmentTabTitle {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string ArticleCreatePageAttachmentUploadText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ArticleCreatePageCategoryLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ArticleCreatePageContentLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article added successfully..
        /// </summary>
        public static string ArticleCreatePageCreateSuccessMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePageCreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article updated successfully..
        /// </summary>
        public static string ArticleCreatePageEditSuccessMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePageEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep as Draft.
        /// </summary>
        public static string ArticleCreatePageIsDraftLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageIsDraftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Article.
        /// </summary>
        public static string ArticleCreatePagePreviewArticle {
            get {
                return ResourceManager.GetString("ArticleCreatePagePreviewArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish End.
        /// </summary>
        public static string ArticleCreatePagePublishEndLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePagePublishEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish End Date is required.
        /// </summary>
        public static string ArticleCreatePagePublishEndRequiredMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePagePublishEndRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Start.
        /// </summary>
        public static string ArticleCreatePagePublishStartLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePagePublishStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Start Date is required.
        /// </summary>
        public static string ArticleCreatePagePublishStartRequiredMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePagePublishStartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Friendly Name.
        /// </summary>
        public static string ArticleCreatePageSefNameLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageSefNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string ArticleCreatePageTagsLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new article to {0}.
        /// </summary>
        public static string ArticleCreatePageTitle {
            get {
                return ResourceManager.GetString("ArticleCreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ArticleCreatePageTitleLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add article to vault.
        /// </summary>
        public static string ArticleCreatePageTitleNoCategory {
            get {
                return ResourceManager.GetString("ArticleCreatePageTitleNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article {0}.
        /// </summary>
        public static string ArticleEditPageTitle {
            get {
                return ResourceManager.GetString("ArticleEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article liked..
        /// </summary>
        public static string ArticleLikeSuccess {
            get {
                return ResourceManager.GetString("ArticleLikeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article search engine friendly name is required.
        /// </summary>
        public static string ArticleSefNameIsRequired {
            get {
                return ResourceManager.GetString("ArticleSefNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Category?.
        /// </summary>
        public static string CategoryArticleListRemoveCategoryConfirmMessage {
            get {
                return ResourceManager.GetString("CategoryArticleListRemoveCategoryConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string CategoryArticlesListEditCatTitle {
            get {
                return ResourceManager.GetString("CategoryArticlesListEditCatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Article.
        /// </summary>
        public static string CategoryArticlesListNewArticleTitle {
            get {
                return ResourceManager.GetString("CategoryArticlesListNewArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles in {0}.
        /// </summary>
        public static string CategoryArticlesListPageTitle {
            get {
                return ResourceManager.GetString("CategoryArticlesListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Article and attachments?.
        /// </summary>
        public static string CategoryArticlesListRemoveArticleConfirmMessage {
            get {
                return ResourceManager.GetString("CategoryArticlesListRemoveArticleConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string CategoryArticlesListRemoveCatTitle {
            get {
                return ResourceManager.GetString("CategoryArticlesListRemoveCatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryCreateFormLabelCategory {
            get {
                return ResourceManager.GetString("CategoryCreateFormLabelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Category.
        /// </summary>
        public static string CategoryCreateFormLabelIsHot {
            get {
                return ResourceManager.GetString("CategoryCreateFormLabelIsHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Category Under.
        /// </summary>
        public static string CategoryCreateFormLabelParent {
            get {
                return ResourceManager.GetString("CategoryCreateFormLabelParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create category.
        /// </summary>
        public static string CategoryCreateFormPageTitle {
            get {
                return ResourceManager.GetString("CategoryCreateFormPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Friendly Name.
        /// </summary>
        public static string CategoryCreateFormSefNameLabel {
            get {
                return ResourceManager.GetString("CategoryCreateFormSefNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category: {0}.
        /// </summary>
        public static string CategoryEditFormPageTitle {
            get {
                return ResourceManager.GetString("CategoryEditFormPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategories.
        /// </summary>
        public static string CategoryListSubCategoryTitle {
            get {
                return ResourceManager.GetString("CategoryListSubCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category added successfully..
        /// </summary>
        public static string CategoryPageCreateSuccessMessage {
            get {
                return ResourceManager.GetString("CategoryPageCreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category updated successfully..
        /// </summary>
        public static string CategoryPageEditSuccessMessage {
            get {
                return ResourceManager.GetString("CategoryPageEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category search engine friendly name is required.
        /// </summary>
        public static string CategorySefNameIsRequired {
            get {
                return ResourceManager.GetString("CategorySefNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article.
        /// </summary>
        public static string DashboardEditArticleText {
            get {
                return ResourceManager.GetString("DashboardEditArticleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Liked Article.
        /// </summary>
        public static string DashboardMostLikedArticleHeader {
            get {
                return ResourceManager.GetString("DashboardMostLikedArticleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Viewed Article.
        /// </summary>
        public static string DashboardMostViewedArticleHeader {
            get {
                return ResourceManager.GetString("DashboardMostViewedArticleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Article Count.
        /// </summary>
        public static string DashboardTotalArticleCountHeader {
            get {
                return ResourceManager.GetString("DashboardTotalArticleCountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View article.
        /// </summary>
        public static string DashboardViewArticleText {
            get {
                return ResourceManager.GetString("DashboardViewArticleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string LandingHotCategoryHeader {
            get {
                return ResourceManager.GetString("LandingHotCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Level Categories.
        /// </summary>
        public static string LandingSidebarCategoryListTitle {
            get {
                return ResourceManager.GetString("LandingSidebarCategoryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Tags.
        /// </summary>
        public static string LandingSidebarTagCloudListTitle {
            get {
                return ResourceManager.GetString("LandingSidebarTagCloudListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string LeftSidebarCategoryListTitle {
            get {
                return ResourceManager.GetString("LeftSidebarCategoryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Article.
        /// </summary>
        public static string LeftSidebarCreateArticle {
            get {
                return ResourceManager.GetString("LeftSidebarCreateArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        public static string LeftSidebarCreateCategory {
            get {
                return ResourceManager.GetString("LeftSidebarCreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LeftSideBarSettings {
            get {
                return ResourceManager.GetString("LeftSideBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string LeftSideBarTagsTitle {
            get {
                return ResourceManager.GetString("LeftSideBarTagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string LeftSidebarUserMenuTitle {
            get {
                return ResourceManager.GetString("LeftSidebarUserMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginFormHeader {
            get {
                return ResourceManager.GetString("LoginFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login To KbVault.
        /// </summary>
        public static string LoginFormPageTitle {
            get {
                return ResourceManager.GetString("LoginFormPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginFormPassword {
            get {
                return ResourceManager.GetString("LoginFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberMe.
        /// </summary>
        public static string LoginFormRememberMe {
            get {
                return ResourceManager.GetString("LoginFormRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginFormSubmitButton {
            get {
                return ResourceManager.GetString("LoginFormSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LoginFormUserName {
            get {
                return ResourceManager.GetString("LoginFormUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Article.
        /// </summary>
        public static string PublicArticleDetailPageEditArticleLabel {
            get {
                return ResourceManager.GetString("PublicArticleDetailPageEditArticleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles in {0}.
        /// </summary>
        public static string PublicCategoryListPageTitle {
            get {
                return ResourceManager.GetString("PublicCategoryListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like this..
        /// </summary>
        public static string PublicILikeThis {
            get {
                return ResourceManager.GetString("PublicILikeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this article.
        /// </summary>
        public static string PublicShareThisTitle {
            get {
                return ResourceManager.GetString("PublicShareThisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles tagged with {0}.
        /// </summary>
        public static string PublicTagListPageTitle {
            get {
                return ResourceManager.GetString("PublicTagListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more....
        /// </summary>
        public static string SearchResultsPageLoadMore {
            get {
                return ResourceManager.GetString("SearchResultsPageLoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for [ {0} ].
        /// </summary>
        public static string SearchResultTitle {
            get {
                return ResourceManager.GetString("SearchResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is required.
        /// </summary>
        public static string SettingsCompanyNameRequiredMessage {
            get {
                return ResourceManager.GetString("SettingsCompanyNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Count must be numeric.
        /// </summary>
        public static string SettingsPageArticleCountNumericErrorMessage {
            get {
                return ResourceManager.GetString("SettingsPageArticleCountNumericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Count Per Category On Landing Page.
        /// </summary>
        public static string SettingsPageArticlePerCatLabel {
            get {
                return ResourceManager.GetString("SettingsPageArticlePerCatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string SettingsPageCompanyNameLabel {
            get {
                return ResourceManager.GetString("SettingsPageCompanyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disqus Short Name.
        /// </summary>
        public static string SettingsPageDisqusShortNameLabel {
            get {
                return ResourceManager.GetString("SettingsPageDisqusShortNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions to be included in indexing (pdf,dox,docx...).
        /// </summary>
        public static string SettingsPageIndexFileExtensionsLabel {
            get {
                return ResourceManager.GetString("SettingsPageIndexFileExtensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbotron Text.
        /// </summary>
        public static string SettingsPageJumbotronTextLabel {
            get {
                return ResourceManager.GetString("SettingsPageJumbotronTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved Successfully..
        /// </summary>
        public static string SettingsPageSaveSuccessfull {
            get {
                return ResourceManager.GetString("SettingsPageSaveSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShareThis public key.
        /// </summary>
        public static string SettingsPageShareThisKeyLabel {
            get {
                return ResourceManager.GetString("SettingsPageShareThisKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag line.
        /// </summary>
        public static string SettingsPageTagLineLabel {
            get {
                return ResourceManager.GetString("SettingsPageTagLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Tags in Vault.
        /// </summary>
        public static string TagListHeader {
            get {
                return ResourceManager.GetString("TagListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag has been removed  successfully..
        /// </summary>
        public static string TagListRemoveSuccessful {
            get {
                return ResourceManager.GetString("TagListRemoveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Tag?.
        /// </summary>
        public static string TagListRemoveTagConfirmMessage {
            get {
                return ResourceManager.GetString("TagListRemoveTagConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string UserListAddNewUser {
            get {
                return ResourceManager.GetString("UserListAddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string UserListAddUserHeader {
            get {
                return ResourceManager.GetString("UserListAddUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserListEditUserEmailLabel {
            get {
                return ResourceManager.GetString("UserListEditUserEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User &quot;{0}&quot;.
        /// </summary>
        public static string UserListEditUserHeader {
            get {
                return ResourceManager.GetString("UserListEditUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string UserListEditUserLastNameLabel {
            get {
                return ResourceManager.GetString("UserListEditUserLastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserListEditUserNameLabel {
            get {
                return ResourceManager.GetString("UserListEditUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password (Again).
        /// </summary>
        public static string UserListEditUserNewPasswordAgainLabel {
            get {
                return ResourceManager.GetString("UserListEditUserNewPasswordAgainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string UserListEditUserNewPasswordLabel {
            get {
                return ResourceManager.GetString("UserListEditUserNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserListEditUserOldPasswordLabel {
            get {
                return ResourceManager.GetString("UserListEditUserOldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string UserListEditUserRoleLabel {
            get {
                return ResourceManager.GetString("UserListEditUserRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserListEditUserUsernameLabel {
            get {
                return ResourceManager.GetString("UserListEditUserUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Users.
        /// </summary>
        public static string UserListHeader {
            get {
                return ResourceManager.GetString("UserListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User?.
        /// </summary>
        public static string UserListRemoveUserConfirmMessage {
            get {
                return ResourceManager.GetString("UserListRemoveUserConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information updated successfully.
        /// </summary>
        public static string UserListUserEditSuccessful {
            get {
                return ResourceManager.GetString("UserListUserEditSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required.
        /// </summary>
        public static string UserListUserOldPasswordRequired {
            get {
                return ResourceManager.GetString("UserListUserOldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string UserProfilePageTitle {
            get {
                return ResourceManager.GetString("UserProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile can&apos;t be updated.
        /// </summary>
        public static string UserProfileUpdateFail {
            get {
                return ResourceManager.GetString("UserProfileUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully.
        /// </summary>
        public static string UserProfileUpdateSuccessful {
            get {
                return ResourceManager.GetString("UserProfileUpdateSuccessful", resourceCulture);
            }
        }
    }
}
