ALTER TABLE dbo.Settings ADD
	AnalyticsAccount nvarchar(50) NULL
GO

ALTER TABLE dbo.KbUser SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Activities
	(
	Id bigint NOT NULL IDENTITY (1, 1),
	UserId bigint NOT NULL,
	ActivityDate datetime2(7) NOT NULL,
	Operation nvarchar(50) NOT NULL,
	Information nvarchar(100) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Activities ADD CONSTRAINT
	PK_Activities PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Activities ADD CONSTRAINT
	FK_Activities_KbUser FOREIGN KEY
	(
	UserId
	) REFERENCES dbo.KbUser
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Activities SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

ALTER TABLE dbo.KbUser SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Category ADD
	Author bigint NOT NULL CONSTRAINT DF_Category_Author DEFAULT 1
GO
ALTER TABLE dbo.Category ADD CONSTRAINT
	FK_Category_KbUser FOREIGN KEY
	(
	Author
	) REFERENCES dbo.KbUser
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Category SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

ALTER TABLE dbo.KbUser SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Settings ADD
	Author bigint NOT NULL CONSTRAINT DF_Settings_Author DEFAULT 1
GO
ALTER TABLE dbo.Settings ADD CONSTRAINT
	FK_Settings_KbUser FOREIGN KEY
	(
	Author
	) REFERENCES dbo.KbUser
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Settings SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

ALTER TABLE dbo.KbUser SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Attachment ADD
	Author bigint NOT NULL CONSTRAINT DF_Attachment_Author DEFAULT 1
GO
ALTER TABLE dbo.Attachment ADD CONSTRAINT
	FK_Attachment_KbUser FOREIGN KEY
	(
	Author
	) REFERENCES dbo.KbUser
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Attachment SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

ALTER TABLE dbo.KbUser SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Tag ADD
	Author bigint NOT NULL CONSTRAINT DF_Tag_Author DEFAULT 1
GO
ALTER TABLE dbo.Tag ADD CONSTRAINT
	FK_Tag_KbUser FOREIGN KEY
	(
	Author
	) REFERENCES dbo.KbUser
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Tag SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

ALTER TABLE dbo.KbUser ADD
	Author bigint NOT NULL CONSTRAINT DF_KbUser_Author DEFAULT 1
GO
ALTER TABLE dbo.KbUser ADD CONSTRAINT
	FK_KbUser_KbUser FOREIGN KEY
	(
	Author
	) REFERENCES dbo.KbUser
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.KbUser SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

ALTER TABLE dbo.KbUser SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.ArticleTag ADD
	Author bigint NOT NULL CONSTRAINT DF_ArticleTag_Author DEFAULT 1
GO
ALTER TABLE dbo.ArticleTag ADD CONSTRAINT
	FK_ArticleTag_KbUser FOREIGN KEY
	(
	Author
	) REFERENCES dbo.KbUser
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.ArticleTag SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
