//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UIResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Date.
        /// </summary>
        internal static string ActivitiesPageDateColumnTitle {
            get {
                return ResourceManager.GetString("ActivitiesPageDateColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records available.
        /// </summary>
        internal static string ActivitiesPageInfoEmptyText {
            get {
                return ResourceManager.GetString("ActivitiesPageInfoEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string ActivitiesPageInformationColumnTitle {
            get {
                return ResourceManager.GetString("ActivitiesPageInformationColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing page {0} of {1}.
        /// </summary>
        internal static string ActivitiesPageInfoText {
            get {
                return ResourceManager.GetString("ActivitiesPageInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string ActivitiesPageOperationColumnTitle {
            get {
                return ResourceManager.GetString("ActivitiesPageOperationColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string ActivitiesPagePaginateFirst {
            get {
                return ResourceManager.GetString("ActivitiesPagePaginateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string ActivitiesPagePaginateLast {
            get {
                return ResourceManager.GetString("ActivitiesPagePaginateLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ActivitiesPagePaginateNext {
            get {
                return ResourceManager.GetString("ActivitiesPagePaginateNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string ActivitiesPagePaginatePrevious {
            get {
                return ResourceManager.GetString("ActivitiesPagePaginatePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string ActivitiesPageTitle {
            get {
                return ResourceManager.GetString("ActivitiesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string ActivitiesPageUserColumnTitle {
            get {
                return ResourceManager.GetString("ActivitiesPageUserColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found sorry :(.
        /// </summary>
        internal static string ActivitiesPageZeroRecords {
            get {
                return ResourceManager.GetString("ActivitiesPageZeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Attachment?.
        /// </summary>
        internal static string ArticleAttachmentRemoveConfirmation {
            get {
                return ResourceManager.GetString("ArticleAttachmentRemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        internal static string ArticleCreatePageArticleTabTitle {
            get {
                return ResourceManager.GetString("ArticleCreatePageArticleTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort Upload.
        /// </summary>
        internal static string ArticleCreatePageAttachmentAbortText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentAbortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Upload.
        /// </summary>
        internal static string ArticleCreatePageAttachmentCancelText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ArticleCreatePageAttachmentDeleteText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string ArticleCreatePageAttachmentDoneText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentDoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Files Here.
        /// </summary>
        internal static string ArticleCreatePageAttachmentDragDropText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentDragDropText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments are available after saving article..
        /// </summary>
        internal static string ArticleCreatePageAttachmentsAfterSaveMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentsAfterSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string ArticleCreatePageAttachmentsHeader {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string ArticleCreatePageAttachmentTabTitle {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string ArticleCreatePageAttachmentUploadText {
            get {
                return ResourceManager.GetString("ArticleCreatePageAttachmentUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string ArticleCreatePageCategoryLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageCategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string ArticleCreatePageContentLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article added successfully..
        /// </summary>
        internal static string ArticleCreatePageCreateSuccessMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePageCreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download attachment.
        /// </summary>
        internal static string ArticleCreatePageDownloadAttachment {
            get {
                return ResourceManager.GetString("ArticleCreatePageDownloadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article updated successfully..
        /// </summary>
        internal static string ArticleCreatePageEditSuccessMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePageEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep as Draft.
        /// </summary>
        internal static string ArticleCreatePageIsDraftLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageIsDraftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Article.
        /// </summary>
        internal static string ArticleCreatePagePreviewArticle {
            get {
                return ResourceManager.GetString("ArticleCreatePagePreviewArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish End.
        /// </summary>
        internal static string ArticleCreatePagePublishEndLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePagePublishEndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish End Date is required.
        /// </summary>
        internal static string ArticleCreatePagePublishEndRequiredMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePagePublishEndRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Start.
        /// </summary>
        internal static string ArticleCreatePagePublishStartLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePagePublishStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Start Date is required.
        /// </summary>
        internal static string ArticleCreatePagePublishStartRequiredMessage {
            get {
                return ResourceManager.GetString("ArticleCreatePagePublishStartRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes attachment..
        /// </summary>
        internal static string ArticleCreatePageRemoveAttachment {
            get {
                return ResourceManager.GetString("ArticleCreatePageRemoveAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Friendly Name.
        /// </summary>
        internal static string ArticleCreatePageSefNameLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageSefNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string ArticleCreatePageTagsLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new article to {0}.
        /// </summary>
        internal static string ArticleCreatePageTitle {
            get {
                return ResourceManager.GetString("ArticleCreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ArticleCreatePageTitleLabel {
            get {
                return ResourceManager.GetString("ArticleCreatePageTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add article to vault.
        /// </summary>
        internal static string ArticleCreatePageTitleNoCategory {
            get {
                return ResourceManager.GetString("ArticleCreatePageTitleNoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article {0}.
        /// </summary>
        internal static string ArticleEditPageTitle {
            get {
                return ResourceManager.GetString("ArticleEditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article liked..
        /// </summary>
        internal static string ArticleLikeSuccess {
            get {
                return ResourceManager.GetString("ArticleLikeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article search engine friendly name is required.
        /// </summary>
        internal static string ArticleSefNameIsRequired {
            get {
                return ResourceManager.GetString("ArticleSefNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Now!.
        /// </summary>
        internal static string BackupPageNewBackup {
            get {
                return ResourceManager.GetString("BackupPageNewBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup / Restore .
        /// </summary>
        internal static string BackupPageTitle {
            get {
                return ResourceManager.GetString("BackupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database successfully restored..
        /// </summary>
        internal static string BackupRestoreSuccessfull {
            get {
                return ResourceManager.GetString("BackupRestoreSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string BackupTableDateColHeader {
            get {
                return ResourceManager.GetString("BackupTableDateColHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string BackupTableRestoreButtonLabel {
            get {
                return ResourceManager.GetString("BackupTableRestoreButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Category?.
        /// </summary>
        internal static string CategoryArticleListRemoveCategoryConfirmMessage {
            get {
                return ResourceManager.GetString("CategoryArticleListRemoveCategoryConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        internal static string CategoryArticlesListEditCatTitle {
            get {
                return ResourceManager.GetString("CategoryArticlesListEditCatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Article.
        /// </summary>
        internal static string CategoryArticlesListNewArticleTitle {
            get {
                return ResourceManager.GetString("CategoryArticlesListNewArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles in {0}.
        /// </summary>
        internal static string CategoryArticlesListPageTitle {
            get {
                return ResourceManager.GetString("CategoryArticlesListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Article and attachments?.
        /// </summary>
        internal static string CategoryArticlesListRemoveArticleConfirmMessage {
            get {
                return ResourceManager.GetString("CategoryArticlesListRemoveArticleConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        internal static string CategoryArticlesListRemoveCatTitle {
            get {
                return ResourceManager.GetString("CategoryArticlesListRemoveCatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string CategoryCreateFormLabelCategory {
            get {
                return ResourceManager.GetString("CategoryCreateFormLabelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string CategoryCreateFormLabelIcon {
            get {
                return ResourceManager.GetString("CategoryCreateFormLabelIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can write name of any font-awesome icon. Try bomb or book to get started ;).
        /// </summary>
        internal static string CategoryCreateFormLabelIconInfo {
            get {
                return ResourceManager.GetString("CategoryCreateFormLabelIconInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Category.
        /// </summary>
        internal static string CategoryCreateFormLabelIsHot {
            get {
                return ResourceManager.GetString("CategoryCreateFormLabelIsHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Category Under.
        /// </summary>
        internal static string CategoryCreateFormLabelParent {
            get {
                return ResourceManager.GetString("CategoryCreateFormLabelParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create category.
        /// </summary>
        internal static string CategoryCreateFormPageTitle {
            get {
                return ResourceManager.GetString("CategoryCreateFormPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engine Friendly Name.
        /// </summary>
        internal static string CategoryCreateFormSefNameLabel {
            get {
                return ResourceManager.GetString("CategoryCreateFormSefNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category: {0}.
        /// </summary>
        internal static string CategoryEditFormPageTitle {
            get {
                return ResourceManager.GetString("CategoryEditFormPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategories.
        /// </summary>
        internal static string CategoryListSubCategoryTitle {
            get {
                return ResourceManager.GetString("CategoryListSubCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category added successfully..
        /// </summary>
        internal static string CategoryPageCreateSuccessMessage {
            get {
                return ResourceManager.GetString("CategoryPageCreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category updated successfully..
        /// </summary>
        internal static string CategoryPageEditSuccessMessage {
            get {
                return ResourceManager.GetString("CategoryPageEditSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category search engine friendly name is required.
        /// </summary>
        internal static string CategorySefNameIsRequired {
            get {
                return ResourceManager.GetString("CategorySefNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article.
        /// </summary>
        internal static string DashboardEditArticleText {
            get {
                return ResourceManager.GetString("DashboardEditArticleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Liked Article.
        /// </summary>
        internal static string DashboardMostLikedArticleHeader {
            get {
                return ResourceManager.GetString("DashboardMostLikedArticleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Viewed Article.
        /// </summary>
        internal static string DashboardMostViewedArticleHeader {
            get {
                return ResourceManager.GetString("DashboardMostViewedArticleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Article Count.
        /// </summary>
        internal static string DashboardTotalArticleCountHeader {
            get {
                return ResourceManager.GetString("DashboardTotalArticleCountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View article.
        /// </summary>
        internal static string DashboardViewArticleText {
            get {
                return ResourceManager.GetString("DashboardViewArticleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        internal static string ErrorPageHeader {
            get {
                return ResourceManager.GetString("ErrorPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Management.
        /// </summary>
        internal static string IndexingLeftMenuTitle {
            get {
                return ResourceManager.GetString("IndexingLeftMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild Indexes.
        /// </summary>
        internal static string IndexingRebuildButtonText {
            get {
                return ResourceManager.GetString("IndexingRebuildButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild Lucene Indexes.
        /// </summary>
        internal static string IndexingRebuildIndexTitle {
            get {
                return ResourceManager.GetString("IndexingRebuildIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Management.
        /// </summary>
        internal static string IndexingRebuildPageTitle {
            get {
                return ResourceManager.GetString("IndexingRebuildPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        internal static string LandingHotCategoryHeader {
            get {
                return ResourceManager.GetString("LandingHotCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Articles.
        /// </summary>
        internal static string LandingLatestArticlesTitle {
            get {
                return ResourceManager.GetString("LandingLatestArticlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Articles.
        /// </summary>
        internal static string LandingPopularArticlesTitle {
            get {
                return ResourceManager.GetString("LandingPopularArticlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Level Categories.
        /// </summary>
        internal static string LandingSidebarCategoryListTitle {
            get {
                return ResourceManager.GetString("LandingSidebarCategoryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Tags.
        /// </summary>
        internal static string LandingSidebarTagCloudListTitle {
            get {
                return ResourceManager.GetString("LandingSidebarTagCloudListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Activities.
        /// </summary>
        internal static string LeftSideBarActivitiesTitle {
            get {
                return ResourceManager.GetString("LeftSideBarActivitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string LeftSideBarBackupTitle {
            get {
                return ResourceManager.GetString("LeftSideBarBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string LeftSidebarCategoryListTitle {
            get {
                return ResourceManager.GetString("LeftSidebarCategoryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Article.
        /// </summary>
        internal static string LeftSidebarCreateArticle {
            get {
                return ResourceManager.GetString("LeftSidebarCreateArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Category.
        /// </summary>
        internal static string LeftSidebarCreateCategory {
            get {
                return ResourceManager.GetString("LeftSidebarCreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string LeftSideBarSettings {
            get {
                return ResourceManager.GetString("LeftSideBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string LeftSideBarTagsTitle {
            get {
                return ResourceManager.GetString("LeftSideBarTagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string LeftSidebarUserMenuTitle {
            get {
                return ResourceManager.GetString("LeftSidebarUserMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginFormHeader {
            get {
                return ResourceManager.GetString("LoginFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login To KbVault.
        /// </summary>
        internal static string LoginFormPageTitle {
            get {
                return ResourceManager.GetString("LoginFormPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginFormPassword {
            get {
                return ResourceManager.GetString("LoginFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberMe.
        /// </summary>
        internal static string LoginFormRememberMe {
            get {
                return ResourceManager.GetString("LoginFormRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginFormSubmitButton {
            get {
                return ResourceManager.GetString("LoginFormSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LoginFormUserName {
            get {
                return ResourceManager.GetString("LoginFormUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        internal static string MainMenuBootstrapToogleTitle {
            get {
                return ResourceManager.GetString("MainMenuBootstrapToogleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Article.
        /// </summary>
        internal static string PublicArticleDetailPageEditArticleLabel {
            get {
                return ResourceManager.GetString("PublicArticleDetailPageEditArticleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles in {0}.
        /// </summary>
        internal static string PublicCategoryListPageTitle {
            get {
                return ResourceManager.GetString("PublicCategoryListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like this..
        /// </summary>
        internal static string PublicILikeThis {
            get {
                return ResourceManager.GetString("PublicILikeThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this article.
        /// </summary>
        internal static string PublicShareThisTitle {
            get {
                return ResourceManager.GetString("PublicShareThisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Articles.
        /// </summary>
        internal static string PublicSimilarArticlesTitle {
            get {
                return ResourceManager.GetString("PublicSimilarArticlesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles tagged with {0}.
        /// </summary>
        internal static string PublicTagListPageTitle {
            get {
                return ResourceManager.GetString("PublicTagListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have published {0} articles..
        /// </summary>
        internal static string PublicTotalArticleCountMessage {
            get {
                return ResourceManager.GetString("PublicTotalArticleCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more....
        /// </summary>
        internal static string SearchResultsPageLoadMore {
            get {
                return ResourceManager.GetString("SearchResultsPageLoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for [ {0} ].
        /// </summary>
        internal static string SearchResultTitle {
            get {
                return ResourceManager.GetString("SearchResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Prefix.
        /// </summary>
        internal static string SettingsArticlePrefixLabel {
            get {
                return ResourceManager.GetString("SettingsArticlePrefixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Prefix Is Required.
        /// </summary>
        internal static string SettingsArticlePrefixRequiredMessage {
            get {
                return ResourceManager.GetString("SettingsArticlePrefixRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Path.
        /// </summary>
        internal static string SettingsBackupPath {
            get {
                return ResourceManager.GetString("SettingsBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder must be writable by MsSQL Service User.  if you want to use a folder under website use ~/Backupfolder syntax..
        /// </summary>
        internal static string SettingsBackupPathWarning {
            get {
                return ResourceManager.GetString("SettingsBackupPathWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is required.
        /// </summary>
        internal static string SettingsCompanyNameRequiredMessage {
            get {
                return ResourceManager.GetString("SettingsCompanyNameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics Account Name.
        /// </summary>
        internal static string SettingsPageAnalyticsAccount {
            get {
                return ResourceManager.GetString("SettingsPageAnalyticsAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics API Key.
        /// </summary>
        internal static string SettingsPageAnalyticsKeyLabel {
            get {
                return ResourceManager.GetString("SettingsPageAnalyticsKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Count must be numeric.
        /// </summary>
        internal static string SettingsPageArticleCountNumericErrorMessage {
            get {
                return ResourceManager.GetString("SettingsPageArticleCountNumericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Count Per Category On Landing Page.
        /// </summary>
        internal static string SettingsPageArticlePerCatLabel {
            get {
                return ResourceManager.GetString("SettingsPageArticlePerCatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string SettingsPageCompanyNameLabel {
            get {
                return ResourceManager.GetString("SettingsPageCompanyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disqus Short Name.
        /// </summary>
        internal static string SettingsPageDisqusShortNameLabel {
            get {
                return ResourceManager.GetString("SettingsPageDisqusShortNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions to be included in indexing (.pdf,.dox,.docx...).
        /// </summary>
        internal static string SettingsPageIndexFileExtensionsLabel {
            get {
                return ResourceManager.GetString("SettingsPageIndexFileExtensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumbotron Text.
        /// </summary>
        internal static string SettingsPageJumbotronTextLabel {
            get {
                return ResourceManager.GetString("SettingsPageJumbotronTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved Successfully..
        /// </summary>
        internal static string SettingsPageSaveSuccessfull {
            get {
                return ResourceManager.GetString("SettingsPageSaveSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShareThis public key.
        /// </summary>
        internal static string SettingsPageShareThisKeyLabel {
            get {
                return ResourceManager.GetString("SettingsPageShareThisKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag line.
        /// </summary>
        internal static string SettingsPageTagLineLabel {
            get {
                return ResourceManager.GetString("SettingsPageTagLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show total number of articles on front page.
        /// </summary>
        internal static string SettingsShowTotalArticleCountOnFrontPage {
            get {
                return ResourceManager.GetString("SettingsShowTotalArticleCountOnFrontPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Tags in Vault.
        /// </summary>
        internal static string TagListHeader {
            get {
                return ResourceManager.GetString("TagListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag has been removed  successfully..
        /// </summary>
        internal static string TagListRemoveSuccessful {
            get {
                return ResourceManager.GetString("TagListRemoveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Tag?.
        /// </summary>
        internal static string TagListRemoveTagConfirmMessage {
            get {
                return ResourceManager.GetString("TagListRemoveTagConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        internal static string UserListAddNewUser {
            get {
                return ResourceManager.GetString("UserListAddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        internal static string UserListAddUserHeader {
            get {
                return ResourceManager.GetString("UserListAddUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UserListEditUserEmailLabel {
            get {
                return ResourceManager.GetString("UserListEditUserEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User &quot;{0}&quot;.
        /// </summary>
        internal static string UserListEditUserHeader {
            get {
                return ResourceManager.GetString("UserListEditUserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string UserListEditUserLastNameLabel {
            get {
                return ResourceManager.GetString("UserListEditUserLastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UserListEditUserNameLabel {
            get {
                return ResourceManager.GetString("UserListEditUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password (Again).
        /// </summary>
        internal static string UserListEditUserNewPasswordAgainLabel {
            get {
                return ResourceManager.GetString("UserListEditUserNewPasswordAgainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string UserListEditUserNewPasswordLabel {
            get {
                return ResourceManager.GetString("UserListEditUserNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string UserListEditUserOldPasswordLabel {
            get {
                return ResourceManager.GetString("UserListEditUserOldPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string UserListEditUserRoleLabel {
            get {
                return ResourceManager.GetString("UserListEditUserRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserListEditUserUsernameLabel {
            get {
                return ResourceManager.GetString("UserListEditUserUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Users.
        /// </summary>
        internal static string UserListHeader {
            get {
                return ResourceManager.GetString("UserListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove User?.
        /// </summary>
        internal static string UserListRemoveUserConfirmMessage {
            get {
                return ResourceManager.GetString("UserListRemoveUserConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information updated successfully.
        /// </summary>
        internal static string UserListUserEditSuccessful {
            get {
                return ResourceManager.GetString("UserListUserEditSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required.
        /// </summary>
        internal static string UserListUserOldPasswordRequired {
            get {
                return ResourceManager.GetString("UserListUserOldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string UserProfilePageTitle {
            get {
                return ResourceManager.GetString("UserProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile can&apos;t be updated.
        /// </summary>
        internal static string UserProfileUpdateFail {
            get {
                return ResourceManager.GetString("UserProfileUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully.
        /// </summary>
        internal static string UserProfileUpdateSuccessful {
            get {
                return ResourceManager.GetString("UserProfileUpdateSuccessful", resourceCulture);
            }
        }
    }
}
